var wonita = [
    ["的", "的", "de5", "of/~'s (possessive particle)/(used after an attribute)/(used to form a nominal expression)/(used at the end of a declarative sentence for emphasis)"],
    ["的", "的", "di2", "really and truly"],
    ["的", "的", "di4", "aim/clear"],
    ["一", "一", "yi1", "one/1/single/a (article)/as soon as/entire/whole/all/throughout/\"one\" radical in Chinese characters (Kangxi radical 1)"],
    ["是", "是", "shi4", "is/are/am/yes/to be"],
    ["人", "人", "ren2", "man/person/people/CL:個|个[ge4],位[wei4]"],
    ["在", "在", "zai4", "(located) at/(to be) in/to exist/in the middle of doing sth/(indicating an action in progress)"],
    ["不", "不", "bu4", "(negative prefix)/not/no"],
    ["有", "有", "you3", "to have/there is/there are/to exist/to be"],
    ["中", "中", "Zhong1", "China/Chinese/surname Zhong"],
    ["中", "中", "zhong1", "within/among/in/middle/center/while (doing sth)/during"],
    ["中", "中", "zhong4", "to hit (the mark)/to be hit by/to suffer/to win (a prize, a lottery)"],
    ["上", "上", "shang3", "see 上聲|上声[shang3 sheng1]"],
    ["上", "上", "shang4", "on top/upon/above/upper/previous/first (of multiple parts)/to climb/to get onto/to go up/to attend (class or university)"],
    ["了", "了", "le5", "(modal particle intensifying preceding clause)/(completed action marker)"],
    ["了", "了", "liao3", "to finish/to achieve/to understand"],
    ["來", "来", "lai2", "to come/to arrive/to come round/ever since/next"],
    ["大", "大", "da4", "big/huge/large/major/great/wide/deep/oldest/eldest"],
    ["大", "大", "dai4", "see 大夫[dai4 fu5]"],
    ["到", "到", "dao4", "to (a place)/until (a time)/up to/to go/to arrive"],
    ["這", "这", "zhe4", "this/these/(commonly pr. [zhei4] before a classifier, esp. in Beijing)"],
    ["為", "为", "wei2", "as (in the capacity of)/to take sth as/to act as/to serve as/to behave as/to become/to be/to do/by (in the passive voice)"],
    ["為", "为", "wei4", "because of/for/to"],
    ["過", "过", "Guo4", "surname Guo"],
    ["過", "过", "guo4", "(experienced action marker)/to cross/to go over/to pass (time)/to celebrate (a holiday)/to live/to get along/excessively/too-"],
    ["以", "以", "Yi3", "abbr. for Israel 以色列[Yi3 se4 lie4]"],
    ["以", "以", "yi3", "to use/according to/so as to/by means of/in order to/by/with/because"],
    ["個", "个", "ge4", "individual/this/that/size/classifier for people or objects in general"],
    ["而", "而", "er2", "and/as well as/and so/but (not)/yet (not)/(indicates causal relation)/(indicates change of state)/(indicates contrast)"],
    ["也", "也", "Ye3", "surname Ye"],
    ["也", "也", "ye3", "also/too/(in Classical Chinese) final particle implying affirmation"],
    ["可", "可", "ke3", "can/may/able to/to approve/to permit/to suit/(particle used for emphasis) certainly/very"],
    ["可", "可", "ke4", "see 可汗[ke4 han2]"],
    ["時", "时", "Shi2", "surname Shi"],
    ["時", "时", "shi2", "o'clock/time/when/hour/season/period"],
    ["就", "就", "jiu4", "at once/right away/only/just (emphasis)/as early as/already/as soon as/then/in that case/as many as/even if/to approach/to move towards/to undertake/to engage in/to suffer/subjected to/to accomplish/to take advantage of/to go with (of foods)/with regard to/concerning"],
    ["於", "于", "Yu2", "surname Yu"],
    ["於", "于", "yu2", "in/at/to/from/by/than/out of"],
    ["於", "於", "wu1", "(literary) Oh!/Ah!"],
    ["生", "生", "sheng1", "to be born/to give birth/life/to grow/raw, uncooked"],
    ["出", "出", "chu1", "to go out/to come out/to occur/to produce/to go beyond/to rise/to put forth/to happen/classifier for dramas, plays, operas etc"],
    ["成", "成", "Cheng2", "surname Cheng"],
    ["成", "成", "cheng2", "to succeed/to finish/to complete/to accomplish/to become/to turn into/to be all right/OK!/one tenth"],
    ["得", "得", "de2", "to obtain/to get/to gain/to catch (a disease)/proper/suitable/proud/contented/to allow/to permit/ready/finished"],
    ["得", "得", "de5", "structural particle: used after a verb (or adjective as main verb), linking it to following phrase indicating effect, degree, possibility etc"],
    ["得", "得", "dei3", "to have to/must/ought to/to need to"],
    ["下", "下", "xia4", "down/downwards/below/lower/later/next (week etc)/second (of two parts)/to decline/to go down/to arrive at (a decision, conclusion etc)"],
    ["後", "后", "hou4", "back/behind/rear/afterwards/after/later"],
    ["會", "会", "hui4", "can/be possible/be able to/will/be likely to/be sure to/to assemble/to meet/to gather/to see/union/group/association/CL:個|个[ge4]/a moment (Taiwan pr. for this sense is [hui3])"],
    ["會", "会", "kuai4", "to balance an account/accountancy/accounting"],
    ["要", "要", "yao1", "to demand/to request/to coerce"],
    ["要", "要", "yao4", "important/vital/to want/will/going to (as future auxiliary)/may/must/(used in a comparison) must be/probably"],
    ["之", "之", "zhi1", "(possessive particle, literary equivalent of 的)/him/her/it"],
    ["對", "对", "dui4", "couple/pair/to be opposite/to oppose/to face/versus/for/to/correct (answer)/to answer/to reply/to direct (towards sth)/right"],
    ["多", "多", "duo1", "many/much/a lot of/numerous/more/in excess/how (to what extent)/multi-/Taiwan pr. [duo2] when it means \"how\""],
    ["自", "自", "zi4", "from/self/oneself/since"],
    ["都", "都", "Du1", "surname Du"],
    ["都", "都", "dou1", "all/both/entirely/(used for emphasis) even/already/(not) at all"],
    ["都", "都", "du1", "capital city/metropolis"],
    ["年", "年", "Nian2", "surname Nian"],
    ["年", "年", "nian2", "year/CL:個|个[ge4]"],
    ["無", "无", "wu2", "-less/not to have/no/none/not/to lack/un-"],
    ["我", "我", "wo3", "I/me/my"],
    ["然", "然", "ran2", "correct/right/so/thus/like this/-ly"],
    ["如", "如", "ru2", "as/as if/such as"],
    ["他", "他", "ta1", "he or him/(used for either sex when the sex is unknown or unimportant)/(used before sb's name for emphasis)/(used as a meaningless mock object)/other/another"],
    ["當", "当", "dang1", "to be/to act as/manage/withstand/when/during/ought/should/match equally/equal/same/obstruct/just at (a time or place)/on the spot/right/just at"],
    ["當", "当", "dang4", "at or in the very same.../suitable/adequate/fitting/proper/to replace/to regard as/to think/to pawn/(coll.) to fail (a student)"],
    ["前", "前", "qian2", "front/forward/ahead/ago/before/first/former/formerly/future/BC (e.g. 前293年)"],
    ["地", "地", "de5", "-ly/structural particle: used before a verb or adjective, linking it to preceding modifying adverbial adjunct"],
    ["地", "地", "di4", "earth/ground/field/place/land/CL:片[pian4]"],
    ["能", "能", "Neng2", "surname Neng"],
    ["能", "能", "neng2", "to be able to/to be capable of/ability/capability/able/capable/can possibly/(usually used in the negative) to have the possibility of"],
    ["說", "说", "shui4", "to persuade"],
    ["說", "说", "shuo1", "to speak/to say/to explain/to scold/to tell off/a theory (usually in compounds such as 日心说 heliocentric theory)"],
    ["心", "心", "xin1", "heart/mind/intention/centre/core/CL:顆|颗[ke1],個|个[ge4]"],
    ["所", "所", "suo3", "actually/place/classifier for houses, small buildings, institutions etc/that which/particle introducing a relative clause or passive/CL:個|个[ge4]"],
    ["現", "现", "xian4", "to appear/present/now/existing/current"],
    ["但", "但", "dan4", "but/yet/however/only/merely/still"],
    ["去", "去", "qu4", "to go/to go to (a place)/to cause to go or send (sb)/to remove/to get rid of/(when used either before or after a verb) to go in order to do sth/to be apart from in space or time/(after a verb of motion indicates movement away from the speaker)/(used after certain verbs to indicate detachment or separation)/(of a time or an event etc) just passed or elapsed"],
    ["們", "们", "men5", "plural marker for pronouns, and nouns referring to individuals"],
    ["意", "意", "Yi4", "Italy/Italian/abbr. for 意大利[Yi4 da4 li4]"],
    ["意", "意", "yi4", "idea/meaning/thought/to think/wish/desire/intention/to expect/to anticipate"],
    ["發", "发", "fa1", "to send out/to show (one's feeling)/to issue/to develop/classifier for gunshots (rounds)"],
    ["家", "家", "Jia1", "surname Jia"],
    ["家", "家", "jia1", "home/family/(polite) my (sister, uncle etc)/classifier for families or businesses/refers to the philosophical schools of pre-Han China/noun suffix for a specialist in some activity, such as a musician or revolutionary, corresponding to English -ist, -er, -ary or -ian/CL:個|个[ge4]"],
    ["實", "实", "shi2", "real/true/honest/really/solid/fruit/seed/definitely"],
    ["因", "因", "yin1", "cause/reason/because"],
    ["事", "事", "shi4", "matter/thing/item/work/affair/CL:件[jian4],樁|桩[zhuang1]"],
    ["經", "经", "Jing1", "surname Jing"],
    ["經", "经", "jing1", "classics/sacred book/scripture/to pass through/to undergo/warp/longitude/abbr. for economics 經濟|经济[jing1 ji4]"],
    ["和", "和", "He2", "surname He/Japanese (food, clothes etc)"],
    ["和", "和", "he2", "and/together with/with/sum/union/peace/harmony/Taiwan pr. [han4] when it means \"and\""],
    ["和", "和", "he4", "cap (a poem)/to respond in singing"],
    ["和", "和", "hu2", "to complete a set in mahjong or playing cards"],
    ["和", "和", "huo2", "soft/warm"],
    ["和", "和", "huo4", "to mix together/to blend"],
    ["開", "开", "kai1", "to open/to start/to turn on/to boil/to write out (a prescription, check, invoice etc)/to operate (vehicle)/abbr. for 開爾文|开尔文 degrees Kelvin"],
    ["與", "与", "yu2", "(same as 歟|欤, final particle expression doubt or surprise, similar to 吗 or 呢)"],
    ["與", "与", "yu3", "and/to give/together with"],
    ["與", "与", "yu4", "take part in"],
    ["只", "只", "zhi3", "only/merely/just/but"],
    ["已", "已", "yi3", "already/to stop/then/afterwards"],
    ["日", "日", "ri4", "sun/day/date, day of the month/abbr. for 日本 Japan"],
    ["同", "同", "tong2", "like/same/similar/together/alike/with"],
    ["分", "分", "fen1", "to divide/to separate/to distribute/to allocate/to distinguish (good and bad)/part or subdivision/fraction/one tenth (of certain units)/unit of length equivalent to 0.33 cm/minute/a point (in sports or games)/0.01 yuan (unit of money)"],
    ["分", "分", "fen4", "part/share/ingredient/component"],
    ["最", "最", "zui4", "most/the most/-est (superlative suffix)"],
    ["此", "此", "ci3", "this/these"],
    ["方", "方", "Fang1", "surname Fang"],
    ["方", "方", "fang1", "square/power or involution (mathematics)/upright/honest/fair and square/direction/side/party (to a contract, dispute etc)/place/method/prescription (medicine)/just when/only or just/classifier for square things/abbr. for square or cubic meter"],
    ["面", "面", "mian4", "face/side/surface/aspect/top/classifier for flat surfaces such as drums, mirrors, flags etc"],
    ["著", "着", "zhao1", "(chess) move/trick/all right!/(dialect) to add"],
    ["著", "着", "zhao2", "to touch/to come in contact with/to feel/to be affected by/to catch fire/to fall asleep/to burn"],
    ["著", "着", "zhe5", "aspect particle indicating action in progress"],
    ["著", "着", "zhuo2", "to wear (clothes)/to contact/to use/to apply"],
    ["著", "著", "zhu4", "to make known/to show/to prove/to write/book/outstanding"],
    ["起", "起", "qi3", "to rise/to raise/to get up/to set out/to start/to appear/to launch/to initiate (action)/to draft/to establish/to get (from a depot or counter)/verb suffix, to start/(before place or time) starting from/classifier for occurrences or unpredictable events: case, instance/classifier for groups: batch, group"],
    ["想", "想", "xiang3", "to think/to believe/to suppose/to wish/to want/to miss (feel wistful about the absence of sb or sth)"],
    ["間", "间", "jian1", "between/among/within a definite time or space/room/section of a room or lateral space between two pairs of pillars/classifier for rooms"],
    ["間", "间", "jian4", "gap/to separate/to thin out (seedlings)/to sow discontent"],
    ["重", "重", "chong2", "to repeat/repetition/again/re-/classifier: layer"],
    ["重", "重", "zhong4", "heavy/serious/to attach importance to"],
    ["天", "天", "tian1", "day/sky/heaven"],
    ["情", "情", "qing2", "feeling/emotion/passion/situation"],
    ["種", "种", "zhong3", "seed/species/kind/type/classifier: type, kind, sort"],
    ["種", "种", "zhong4", "to plant/to grow/to cultivate"],
    ["行", "行", "hang2", "a row/series/age order (of brothers)/profession/professional/relating to company"],
    ["行", "行", "xing2", "to walk/to go/to travel/a visit/temporary/makeshift/current/in circulation/to do/to perform/capable/competent/effective/all right/OK!/will do"],
    ["行", "行", "xing4", "behavior/conduct"],
    ["外", "外", "wai4", "outside/in addition/foreign/external"],
    ["十", "十", "shi2", "ten/10"],
    ["其", "其", "qi2", "his/her/its/theirs/that/such/it (refers to sth preceding it)"],
    ["好", "好", "hao3", "good/well/proper/good to/easy to/very/so/(suffix indicating completion or readiness)/(of an unmarried couple) to be close/to be keen on each other"],
    ["好", "好", "hao4", "to be fond of/to have a tendency to/to be prone to"],
    ["從", "从", "Cong2", "surname Cong"],
    ["從", "从", "cong1", "lax/yielding/unhurried"],
    ["從", "从", "cong2", "from/via/passing through/through (a gap)/past/ever (followed by negative, meaning never)/(formerly pr. [zong4] and related to 縱|纵) to follow/to comply with/to obey/to join/to engage in/adopting some mode of action or attitude/follower/retainer/accessory/accomplice/related by common paternal grandfather or earlier ancestor"],
    ["從", "从", "zong4", "second cousin"],
    ["子", "子", "zi3", "son/child/seed/egg/small thing/1st earthly branch: 11 p.m.-1 a.m., midnight, 11th solar month (7th December to 5th January), year of the Rat/Viscount, fourth of five orders of nobility 五等爵位[wu3 deng3 jue2 wei4]"],
    ["子", "子", "zi5", "(noun suffix)"],
    ["作", "作", "zuo4", "to do/to grow/to write or compose/to pretend/to regard as/to feel/writings or works"],
    ["動", "动", "dong4", "to use/to act/to move/to change/abbr. for 動詞|动词[dong4 ci2], verb"],
    ["些", "些", "xie1", "some/few/several/measure word indicating a small amount or small number (greater than 1)"],
    ["小", "小", "xiao3", "small/tiny/few/young"],
    ["那", "那", "na3", "variant of 哪[na3]"],
    ["那", "那", "na4", "that/those/then (in that case)/commonly pr. [nei4] before a classifier, esp. in Beijing"],
    ["看", "看", "kan1", "to look after/to take care of/to watch/to guard"],
    ["看", "看", "kan4", "to see/to look at/to read/to watch/to consider/to regard as/to view as/to treat as/to judge/(after repeated verb) to give it a try/depending on (how you're judging)/to visit/to call on/to treat (an illness)/to look after/Watch out! (for a danger)"],
    ["用", "用", "yong4", "to use/to employ/to have to/to eat or drink/expense or outlay/usefulness/hence/therefore"],
    ["正", "正", "zheng1", "first month of the lunar year"],
    ["正", "正", "zheng4", "just (right)/main/upright/straight/correct/positive/greater than zero/principle"],
    ["三", "三", "San1", "surname San"],
    ["三", "三", "san1", "three/3"],
    ["還", "还", "Huan2", "surname Huan"],
    ["還", "还", "hai2", "still/still in progress/still more/yet/even more/in addition/fairly/passably (good)/as early as/even/also/else"],
    ["還", "还", "huan2", "to pay back/to return"],
    ["道", "道", "dao4", "direction/way/road/path/principle/truth/morality/reason/skill/method/Dao (of Daoism)/to say/to speak/to talk/classifier for long thin stretches, rivers, roads etc/province (of Korea do 도, and formerly Japan dō)/CL:條|条[tiao2],股[gu3]"],
    ["再", "再", "zai4", "again/once more/re-/second/another/then (after sth, and not until then)"],
    ["理", "理", "li3", "texture/grain (of wood)/inner essence/intrinsic order/reason/logic/truth/science/natural science (esp. physics)/to manage/to pay attention to/to run (affairs)/to handle/to put in order/to tidy up"],
    ["長", "长", "chang2", "length/long/forever/always/constantly"],
    ["長", "长", "zhang3", "chief/head/elder/to grow/to develop/to increase/to enhance"],
    ["國", "国", "Guo2", "surname Guo"],
    ["國", "国", "guo2", "country/nation/state/national/CL:個|个[ge4]"],
    ["知", "知", "zhi1", "to know/to be aware"],
    ["高", "高", "Gao1", "surname Gao"],
    ["高", "高", "gao1", "high/tall/above average/loud/your (honorific)"],
    ["明", "明", "Ming2", "Ming Dynasty (1368-1644)/surname Ming/Ming (c. 2000 BC), fourth of the legendary Flame Emperors, 炎帝[Yan2 di4] descended from Shennong 神農|神农[Shen2 nong2] Farmer God"],
    ["明", "明", "ming2", "bright/opposite: dark 暗[an4]/(of meaning) clear/to understand/next/public or open/wise/generic term for a sacrifice to the gods"],
    ["又", "又", "you4", "(once) again/also/both... and.../and yet/(used for emphasis) anyway"],
    ["進", "进", "jin4", "to advance/to enter/to come (or go) into/to receive or admit/to eat or drink/to submit or present/(used after a verb) into, in/to score a goal"],
    ["相", "相", "Xiang1", "surname Xiang"],
    ["相", "相", "xiang1", "each other/one another/mutually"],
    ["相", "相", "xiang4", "appearance/portrait/picture"],
    ["更", "更", "geng1", "to change or replace/to experience/one of the five two hour periods into which the night was formerly divided/watch (e.g. of a sentry or guard)"],
    ["更", "更", "geng4", "more/even more/further/still/still more"],
    ["兩", "两", "liang3", "two/both/some/a few/tael, unit of weight equal to 50 grams (modern) or 1⁄16 of a catty 斤[jin1] (old)"],
    ["麼", "么", "ma2", "exclamatory final particle"],
    ["麼", "么", "ma5", "interrogative final particle"],
    ["麼", "么", "me5", "suffix, used to form interrogative 甚麼|什么, what?, indefinite 這麼|这么 thus etc"],
    ["麼", "麽", "mo2", "tiny/insignificant"],
    ["本", "本", "ben3", "roots or stems of plants/origin/source/this/the current/root/foundation/basis/classifier for books, periodicals, files etc/originally"],
    ["沒", "没", "mei2", "(negative prefix for verbs)/have not/not"],
    ["沒", "没", "mo4", "drowned/to end/to die/to inundate"],
    ["卻", "却", "que4", "but/yet/however/while/to go back/to decline/to retreat/nevertheless/even though"],
    ["法", "法", "Fa3", "France/French/abbr. for 法國|法国[Fa3 guo2]"],
    ["法", "法", "fa3", "law/method/way/Buddhist teaching/Legalist"],
    ["定", "定", "ding4", "to set/to fix/to determine/to decide/to order"],
    ["樣", "样", "yang4", "manner/pattern/way/appearance/shape/CL:個|个[ge4]"],
    ["使", "使", "shi3", "to make/to cause/to enable/to use/to employ/to send/to instruct sb to do sth/envoy/messenger"],
    ["者", "者", "zhe3", "(after a verb or adjective) one who (is) .../(after a noun) person involved in .../-er/-ist/(used after a number or 後|后[hou4] or 前[qian2] to refer to sth mentioned previously)/(used after a term, to mark a pause before defining the term)/(old) (used at the end of a command)/(old) this"],
    ["力", "力", "Li4", "surname Li"],
    ["力", "力", "li4", "power/force/strength/ability/strenuously"],
    ["才", "才", "cai2", "ability/talent/sb of a certain type/a capable individual/only/only then/just now"],
    ["二", "二", "er4", "two/2/stupid (Beijing dialect)"],
    ["由", "由", "you2", "to follow/from/it is for...to/reason/cause/because of/due to/to/to leave it (to sb)/by (introduces passive verb)"],
    ["或", "或", "huo4", "maybe/perhaps/might/possibly/or"],
    ["等", "等", "deng3", "class/rank/grade/equal to/same as/to wait for/to await/et cetera/and so on/et al. (and other authors)/after/as soon as/once"],
    ["點", "点", "dian3", "point/dot/drop/speck/o'clock/point (in space or time)/to draw a dot/to check on a list/to choose/to order (food in a restaurant)/to touch briefly/to hint/to light/to ignite/to pour a liquid drop by drop/(old) one fifth of a two-hour watch 更[geng1]/dot stroke in Chinese characters/classifier for items"],
    ["見", "见", "jian4", "to see/to meet/to appear (to be sth)/to interview"],
    ["見", "见", "xian4", "to appear"],
    ["全", "全", "Quan2", "surname Quan"],
    ["全", "全", "quan2", "all/whole/entire/every/complete"],
    ["至", "至", "zhi4", "to arrive/most/to/until"],
    ["果", "果", "guo3", "fruit/result/resolute/indeed/if really"],
    ["真", "真", "zhen1", "really/truly/indeed/real/true/genuine"],
    ["代", "代", "dai4", "to substitute/to act on behalf of others/to replace/generation/dynasty/age/period/(historical) era/(geological) eon"],
    ["問", "问", "wen4", "to ask"],
    ["何", "何", "He2", "surname He"],
    ["何", "何", "he2", "what/how/why/which/carry"],
    ["學", "学", "xue2", "to learn/to study/science/-ology"],
    ["關", "关", "Guan1", "surname Guan"],
    ["關", "关", "guan1", "mountain pass/to close/to shut/to turn off/to concern/to involve"],
    ["美", "美", "Mei3", "the Americas/abbr. for 美洲[Mei3 zhou1]/USA/abbr. for 美國|美国[Mei3 guo2]"],
    ["美", "美", "mei3", "beautiful/very satisfactory/good/to be pleased with oneself"],
    ["世", "世", "Shi4", "surname Shi"],
    ["世", "世", "shi4", "life/age/generation/era/world/lifetime/epoch/descendant/noble"],
    ["新", "新", "Xin1", "abbr. for Xinjiang 新疆[Xin1 jiang1] or Singapore 新加坡[Xin1 jia1 po1]"],
    ["新", "新", "xin1", "new/newly/meso- (chemistry)"],
    ["處", "处", "chu3", "to reside/to live/to dwell/to be in/to be situated at/to stay/to get along with/to be in a position of/to deal with/to discipline/to punish"],
    ["處", "处", "chu4", "place/location/spot/point/office/department/bureau/respect/classifier for locations or items of damage: spot, point"],
    ["入", "入", "ru4", "to enter/to go into/to join/to become a member of/to confirm or agree with/abbr. for 入聲|入声[ru4 sheng1]"],
    ["並", "并", "bing4", "and/furthermore/also/together with/(not) at all/simultaneously/to combine/to join/to merge"],
    ["感", "感", "gan3", "to feel/to move/to touch/to affect"],
    ["應", "应", "Ying4", "surname Ying"],
    ["應", "应", "ying1", "to agree (to do sth)/should/ought to"],
    ["應", "应", "ying4", "to answer/to respond/to comply with/to deal or cope with"],
    ["很", "很", "hen3", "(adverb of degree)/quite/very/awfully"],
    ["身", "身", "shen1", "body/life/oneself/personally/one's morality and conduct/the main part of a structure or body/pregnant/classifier for sets of clothes: suit, twinset/Kangxi radical 158"],
    ["次", "次", "ci4", "next in sequence/second/the second (day, time etc)/secondary/vice-/sub-/infra-/inferior quality/substandard/order/sequence/hypo- (chemistry)/classifier for enumerated events: time"],
    ["受", "受", "shou4", "to receive/to accept/to suffer/subjected to/to bear/to stand/pleasant/(passive marker)"],
    ["幾", "几", "ji1", "almost"],
    ["幾", "几", "ji3", "how much/how many/several/a few"],
    ["頭", "头", "tou2", "head/hair style/the top/end/beginning or end/a stub/remnant/chief/boss/side/aspect/first/leading/classifier for pigs or livestock/CL:個|个[ge4]"],
    ["頭", "头", "tou5", "suff. for nouns"],
    ["向", "向", "Xiang4", "surname Xiang"],
    ["向", "向", "xiang4", "towards/to face/to turn towards/direction/to support/to side with/shortly before/formerly/always/all along"],
    ["常", "常", "Chang2", "surname Chang"],
    ["常", "常", "chang2", "always/ever/often/frequently/common/general/constant"],
    ["內", "内", "nei4", "inside/inner/internal/within/interior"],
    ["體", "体", "ti3", "body/form/style/system"],
    ["少", "少", "shao3", "few/little/lack"],
    ["少", "少", "shao4", "young"],
    ["必", "必", "bi4", "certainly/must/will/necessarily"],
    ["結", "结", "jie1", "to bear fruit/to produce/firm/solid"],
    ["結", "结", "jie2", "knot/sturdy/bond/to tie/to bind/to check out (of a hotel)"],
    ["難", "难", "nan2", "difficult (to...)/problem/difficulty/difficult/not good"],
    ["難", "难", "nan4", "disaster/distress/to scold"],
    ["化", "化", "hua1", "variant of 花"],
    ["化", "化", "hua4", "to make into/to change into/-ization/to ... -ize/to transform/abbr. for 化學|化学[hua4 xue2]"],
    ["度", "度", "du4", "to pass/to spend (time)/measure/limit/extent/degree of intensity/degree (angles, temperature etc)/kilowatt-hour/classifier for events and occurrences"],
    ["度", "度", "duo2", "to estimate"],
    ["文", "文", "Wen2", "surname Wen"],
    ["文", "文", "wen2", "language/culture/writing/formal/literary/gentle/(old) classifier for coins/Kangxi radical 118"],
    ["主", "主", "zhu3", "owner/master/host/individual or party concerned/God/Lord/main/to indicate or signify/trump card (in card games)"],
    ["回", "回", "hui2", "to circle/to go back/to turn around/to answer/to return/to revolve/Hui ethnic group (Chinese Muslims)/time/classifier for acts of a play/section or chapter (of a classic book)"],
    ["活", "活", "huo2", "to live/alive/living/work/workmanship"],
    ["許", "许", "Xu3", "surname Xu"],
    ["許", "许", "xu3", "to allow/to permit/to promise/to praise/somewhat/perhaps"],
    ["性", "性", "xing4", "nature/character/property/quality/attribute/sexuality/sex/gender/suffix forming adjective from verb/suffix forming noun from adjective, corresponding to -ness or -ity/essence/CL:個|个[ge4]"],
    ["變", "变", "bian4", "to change/to become different/to transform/to vary/rebellion"],
    ["被", "被", "bei4", "quilt/by/(indicates passive-voice clauses)/(literary) to cover/to meet with"],
    ["平", "平", "Ping2", "surname Ping"],
    ["平", "平", "ping2", "flat/level/equal/to tie (make the same score)/to draw (score)/calm/peaceful/see also 平聲|平声[ping2 sheng1]"],
    ["近", "近", "jin4", "near/close to/approximately"],
    ["將", "将", "jiang1", "will/shall/to use/to take/to checkmate/just a short while ago"],
    ["將", "将", "jiang4", "general/commander-in-chief (military)/king (chess piece)/to command/to lead"],
    ["將", "将", "qiang1", "to desire/to invite/to request"],
    ["把", "把", "ba3", "to hold/to contain/to grasp/to take hold of/handle/particle marking the following noun as a direct object/classifier for objects with handle/classifier for small objects: handful"],
    ["把", "把", "ba4", "handle"],
    ["像", "像", "xiang4", "to resemble/to be like/to look as if/such as/appearance/image/portrait/image under a mapping (math.)"],
    ["今", "今", "jin1", "today/modern/present/current/this/now"],
    ["氣", "气", "qi4", "gas/air/smell/weather/to make angry/to annoy/to get angry/vital energy/qi"],
    ["及", "及", "ji2", "and/to reach/up to/in time for"],
    ["己", "己", "ji3", "self/oneself/sixth of 10 heavenly stems 十天干/sixth in order/letter \"F\" or roman \"VI\" in list \"A, B, C\", or \"I, II, III\" etc/hexa"],
    ["四", "四", "si4", "four/4"],
    ["表", "表", "biao3", "exterior surface/family relationship via females/to show (one's opinion)/a model/a table (listing information)/a form/a meter (measuring sth)"],
    ["原", "原", "yuan2", "former/original/primary/raw/level/cause/source"],
    ["位", "位", "wei4", "position/location/place/seat/classifier for people (honorific)/classifier for binary bits (e.g. 十六位 16-bit or 2 bytes)"],
    ["望", "望", "wang4", "full moon/to hope/to expect/to visit/to gaze (into the distance)/to look towards/towards"],
    ["目", "目", "mu4", "eye/item/section/list/catalogue/table of contents/order (taxonomy)/goal/name/title"],
    ["立", "立", "Li4", "surname Li"],
    ["立", "立", "li4", "to stand/to set up/to establish/to lay down/to draw up/at once/immediately"],
    ["風", "风", "feng1", "wind/news/style/custom/manner/CL:陣|阵[zhen4],絲|丝[si1]"],
    ["界", "界", "jie4", "boundary/scope/extent/circles/group/kingdom (taxonomy)"],
    ["滿", "满", "Man3", "Manchu ethnic group"],
    ["滿", "满", "man3", "to fill/full/filled/packed/fully/completely/quite/to reach the limit/to satisfy/satisfied/contented"],
    ["公", "公", "gong1", "public/collectively owned/common/international (e.g. high seas, metric system, calendar)/make public/fair/just/Duke, highest of five orders of nobility 五等爵位[wu3 deng3 jue2 wei4]/honorable (gentlemen)/father-in-law/male (animal)"],
    ["什", "什", "shi2", "ten (used in fractions, writing checks etc)/assorted/miscellaneous"],
    ["物", "物", "wu4", "thing/object/matter/abbr. for physics 物理"],
    ["解", "解", "Xie4", "surname Xie"],
    ["解", "解", "jie3", "to divide/to break up/to split/to separate/to dissolve/to solve/to melt/to remove/to untie/to loosen/to open/to emancipate/to explain/to understand/to know/a solution/a dissection"],
    ["解", "解", "jie4", "to transport under guard"],
    ["解", "解", "xie4", "acrobatic display (esp. on horseback) (old)/variant of 懈[xie4] and 邂[xie4] (old)"],
    ["總", "总", "zong3", "always/to assemble/gather/total/overall/head/chief/general/in every case"],
    ["直", "直", "Zhi2", "surname Zhi/Zhi (c. 2000 BC), fifth of the legendary Flame Emperors 炎帝[Yan2 di4] descended from Shennong 神農|神农[Shen2 nong2] Farmer God"],
    ["直", "直", "zhi2", "straight/to straighten/fair and reasonable/frank/straightforward/(indicates continuing motion or action)/vertical/vertical downward stroke in Chinese characters"],
    ["名", "名", "ming2", "name/noun (part of speech)/place (e.g. among winners)/famous/classifier for people"],
    ["加", "加", "Jia1", "abbr. for Canada 加拿大[Jia1 na2 da4]"],
    ["加", "加", "jia1", "to add/plus"],
    ["太", "太", "tai4", "highest/greatest/too (much)/very/extremely"],
    ["則", "则", "ze2", "conjunction used to express contrast with a previous sentence or clause/standard/norm/rule/to imitate/to follow/then/principle/classifier for written items (such as an official statement)"],
    ["先", "先", "xian1", "early/prior/former/in advance/first"],
    ["未", "未", "wei4", "not yet/did not/have not/not/8th earthly branch: 1-3 p.m., 6th solar month (7th July-6th August), year of the Sheep"],
    ["民", "民", "Min2", "surname Min"],
    ["民", "民", "min2", "the people/nationality/citizen"],
    ["手", "手", "shou3", "hand/(formal) to hold/person engaged in certain types of work/person skilled in certain types of work/personal(ly)/convenient/CL:雙|双[shuang1],隻|只[zhi1]"],
    ["光", "光", "guang1", "light/ray/CL:道[dao4]/bright/only/merely/to use up"],
    ["接", "接", "jie1", "to receive/to answer (the phone)/to meet or welcome sb/to connect/to catch/to join/to extend/to take one's turn on duty/to take over for sb"],
    ["合", "合", "ge3", "100 ml/one-tenth of a peck/measure for dry grain equal to one-tenth of sheng 升 or liter, or one-hundredth dou 斗"],
    ["合", "合", "he2", "to close/to join/to fit/to be equal to/whole/together/round (in battle)/conjunction (astronomy)/1st note of pentatonic scale/old variant of 盒[he2]"],
    ["比", "比", "Bi3", "Belgium/Belgian/abbr. for 比利時|比利时[Bi3 li4 shi2]"],
    ["比", "比", "bi3", "(particle used for comparison and \"-er than\")/to compare/to contrast/to gesture (with hands)/ratio"],
    ["比", "比", "bi4", "to associate with/to be near"],
    ["走", "走", "zou3", "to walk/to go/to run/to move (of vehicle)/to visit/to leave/to go away/to die (euph.)/from/through/away (in compound verbs, such as 撤走)/to change (shape, form, meaning)"],
    ["言", "言", "yan2", "words/speech/to say/to talk"],
    ["言", "讠", "yan2", "\"speech\" or \"words\" radical in Chinese characters (Kangxi radical 149)/see also 言字旁[yan2 zi4 pang2]"],
    ["提", "提", "ti2", "to carry (hanging down from the hand)/to lift/to put forward/to mention/to raise (an issue)/upwards character stroke/lifting brush stroke (in painting)/scoop for measuring liquid"],
    ["機", "机", "Ji1", "surname Ji"],
    ["機", "机", "ji1", "machine/engine/opportunity/intention/aircraft/pivot/crucial point/flexible (quick-witted)/organic/CL:臺|台[tai2]"],
    ["深", "深", "shen1", "close/deep/late/profound/dark (of color, water etc)"],
    ["話", "话", "hua4", "dialect/language/spoken words/speech/talk/words/conversation/what sb said/CL:種|种[zhong3],席[xi2],句[ju4],口[kou3],番[fan1]"],
    ["視", "视", "shi4", "to look at/to regard/to inspect"],
    ["做", "做", "zuo4", "to do/to make/to produce/to write/to compose/to act as/to engage in/to hold (a party)/to be/to become/to function (in some capacity)/to serve as/to be used for/to form (a bond or relationship)/to pretend/to feign/to act a part/to put on appearance"],
    ["別", "别", "Bie2", "surname Bie"],
    ["別", "别", "bie2", "to leave/to depart/to separate/to distinguish/to classify/other/another/do not/must not/to pin"]
];